version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '3992:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - database-network 

  cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '3993:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  database-network:
    driver: bridge